language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.0
      
    # The SDK version used to compile your project
    - android-23

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22

  # https://stackoverflow.com/a/40144426/7797448
  licenses:
    - android-sdk-license-.+
    - '.+'

# https://stackoverflow.com/a/42736695/7797448
before_install:
  - mkdir -p "$ANDROID_HOME/licenses"
  - yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"

script: Save/gradlew -p Save test
